export type CountryDDIPhoneCodeType = {
  name: string
  code: string
  ddi: string
}

export const countries_ddi_phone_code: CountryDDIPhoneCodeType[] = [
  { name: 'Afghanistão', code: 'AF', ddi: '93' },
  { name: 'África do Sul', code: 'ZA', ddi: '27' },
  { name: 'Albânia', code: 'AL', ddi: '355' },
  { name: 'Alemanha', code: 'DE', ddi: '49' },
  { name: 'Andora', code: 'AD', ddi: '376' },
  { name: 'Angola', code: 'AO', ddi: '244' },
  { name: 'Anguilla', code: 'AI', ddi: '1 264' },
  { name: 'Antarctica', code: 'AQ', ddi: '672' },
  { name: 'Antígua e Barbuda', code: 'AG', ddi: '1 268' },
  { name: 'Argentina', code: 'AR', ddi: '54' },
  { name: 'Argélia', code: 'DZ', ddi: '213' },
  { name: 'Arménia', code: 'AM', ddi: '374' },
  { name: 'Aruba', code: 'AW', ddi: '297' },
  { name: 'Arábia Saudita', code: 'SA', ddi: '966' },
  { name: 'Austrália', code: 'AU', ddi: '61' },
  { name: 'Áustria', code: 'AT', ddi: '43' },
  { name: 'Azerbaijão', code: 'AZ', ddi: '994' },
  { name: 'Bahamas', code: 'BS', ddi: '1 242' },
  { name: 'Bahrein', code: 'BH', ddi: '973' },
  { name: 'Bangladesh', code: 'BD', ddi: '880' },
  { name: 'Barbados', code: 'BB', ddi: '1 246' },
  { name: 'Bélgica', code: 'BE', ddi: '32' },
  { name: 'Belize', code: 'BZ', ddi: '501' },
  { name: 'Benim', code: 'BJ', ddi: '229' },
  { name: 'Bermuda', code: 'BM', ddi: '1 441' },
  { name: 'Butão', code: 'BT', ddi: '975' },
  { name: 'Bielorrússia', code: 'BY', ddi: '375' },
  { name: 'Bolívia', code: 'BO', ddi: '591' },
  { name: 'Bósnia e Herzegovina', code: 'BA', ddi: '387' },
  { name: 'Botswana', code: 'BW', ddi: '267' },
  { name: 'Brasil', code: 'BR', ddi: '55' },
  { name: 'Brunei', code: 'BN', ddi: '673' },
  { name: 'Bulgária', code: 'BG', ddi: '359' },
  { name: 'Burkina Faso', code: 'BF', ddi: '226' },
  { name: 'Myanmar (Burma)', code: 'MM', ddi: '95' },
  { name: 'Burundi', code: 'BI', ddi: '257' },
  { name: 'Camarões', code: 'CM', ddi: '237' },
  { name: 'Cabo Verde', code: 'CV', ddi: '238' },
  { name: 'Camboja', code: 'KH', ddi: '855' },
  { name: 'Canadá', code: 'CA', ddi: '1' },
  { name: 'Catar', code: 'QA', ddi: '974' },
  { name: 'Chad', code: 'TD', ddi: '235' },
  { name: 'Chile', code: 'CL', ddi: '56' },
  { name: 'China', code: 'CN', ddi: '86' },
  { name: 'Chipre', code: 'CY', ddi: '357' },
  { name: 'Christmas Island', code: 'CX', ddi: '61' },
  { name: 'Cingapura', code: 'SG', ddi: '65' },
  { name: 'Colômbia', code: 'CO', ddi: '57' },
  { name: 'Comores', code: 'KM', ddi: '269' },
  { name: 'Coreia do Norte', code: 'KP', ddi: '850' },
  { name: 'Coreia do Sul', code: 'KR', ddi: '82' },
  { name: 'Costa do Marfim', code: 'CI', ddi: '225' },
  { name: 'Costa Rica', code: 'CR', ddi: '506' },
  { name: 'Croácia', code: 'HR', ddi: '385' },
  { name: 'Cuba', code: 'CU', ddi: '53' },
  { name: 'Dinamarca', code: 'DK', ddi: '45' },
  { name: 'Djibouti', code: 'DJ', ddi: '253' },
  { name: 'Dominica', code: 'DM', ddi: '1 767' },
  { name: 'Egito', code: 'EG', ddi: '20' },
  { name: 'El Salvador', code: 'SV', ddi: '503' },
  { name: 'Emirados Árabes Unidos', code: 'AE', ddi: '971' },
  { name: 'Equador', code: 'EC', ddi: '593' },
  { name: 'Eritreia', code: 'ER', ddi: '291' },
  { name: 'Estónia', code: 'EE', ddi: '372' },
  { name: 'Espanha', code: 'ES', ddi: '34' },
  { name: 'Etiópia', code: 'ET', ddi: '251' },
  { name: 'Fiji', code: 'FJ', ddi: '679' },
  { name: 'Finlândia', code: 'FI', ddi: '358' },
  { name: 'França', code: 'FR', ddi: '33' },
  { name: 'Gabão', code: 'GA', ddi: '241' },
  { name: 'Gâmbia', code: 'GM', ddi: '220' },
  { name: 'Geórgia', code: 'GE', ddi: '995' },
  { name: 'Gana', code: 'GH', ddi: '233' },
  { name: 'Gibraltar', code: 'GI', ddi: '350' },
  { name: 'Grécia', code: 'GR', ddi: '30' },
  { name: 'Groelândia', code: 'GL', ddi: '299' },
  { name: 'Granada', code: 'GD', ddi: '1 473' },
  { name: 'Guam', code: 'GU', ddi: '1 671' },
  { name: 'Guatemala', code: 'GT', ddi: '502' },
  { name: 'Guiana', code: 'GY', ddi: '592' },
  { name: 'Guiné', code: 'GN', ddi: '224' },
  { name: 'Guiné Equatorial', code: 'GQ', ddi: '240' },
  { name: 'Guiné-Bissau', code: 'GW', ddi: '245' },
  { name: 'Haiti', code: 'HT', ddi: '509' },
  { name: 'Honduras', code: 'HN', ddi: '504' },
  { name: 'Hong Kong', code: 'HK', ddi: '852' },
  { name: 'Hungria', code: 'HU', ddi: '36' },
  { name: 'Islândia', code: 'IS', ddi: '354' },
  { name: 'Ilhas Cayman', code: 'KY', ddi: '1 345' },
  { name: 'Ilhas Cocos (Keeling)', code: 'CC', ddi: '61' },
  { name: 'Ilha de Man', code: 'IM', ddi: '44' },
  { name: 'Ilhas Cook', code: 'CK', ddi: '682' },
  { name: 'Ilhas Falkland (Malvinas)', code: 'FK', ddi: '500' },
  { name: 'Ilhas Feroé', code: 'FO', ddi: '298' },
  { name: 'Ilhas Mariana do Norte', code: 'MP', ddi: '1 670' },
  { name: 'Ilhas Marshall', code: 'MH', ddi: '692' },
  { name: 'Ilhas Pitcairn', code: 'PN', ddi: '870' },
  { name: 'Ilhas Salomão', code: 'SB', ddi: '677' },
  { name: 'Ilhas Turcas e Caicos', code: 'TC', ddi: '1 649' },
  { name: 'Ilhas Virgens Americanas', code: 'VI', ddi: '1 340' },
  { name: 'Ilhas Virgens Britânicas', code: 'VG', ddi: '1 284' },
  { name: 'India', code: 'IN', ddi: '91' },
  { name: 'Indonésia', code: 'ID', ddi: '62' },
  { name: 'Inglaterra (Reino Unido)', code: 'GB', ddi: '44' },
  { name: 'Irã', code: 'IR', ddi: '98' },
  { name: 'Iraque', code: 'IQ', ddi: '964' },
  { name: 'Irlanda', code: 'IE', ddi: '353' },
  { name: 'Israel', code: 'IL', ddi: '972' },
  { name: 'Itália', code: 'IT', ddi: '39' },
  { name: 'Jamaica', code: 'JM', ddi: '1 876' },
  { name: 'Japão', code: 'JP', ddi: '81' },
  { name: 'Jordânia', code: 'JO', ddi: '962' },
  { name: 'Cazaquistão', code: 'KZ', ddi: '7' },
  { name: 'Quénia (Kenya)', code: 'KE', ddi: '254' },
  { name: 'Kiribati', code: 'KI', ddi: '686' },
  { name: 'Kuwait', code: 'KW', ddi: '965' },
  { name: 'Quirguistão', code: 'KG', ddi: '996' },
  { name: 'Laos', code: 'LA', ddi: '856' },
  { name: 'Letônia', code: 'LV', ddi: '371' },
  { name: 'Líbano', code: 'LB', ddi: '961' },
  { name: 'Lesoto', code: 'LS', ddi: '266' },
  { name: 'Libéria', code: 'LR', ddi: '231' },
  { name: 'Líbia', code: 'LY', ddi: '218' },
  { name: 'Liechtenstein', code: 'LI', ddi: '423' },
  { name: 'Lituânia', code: 'LT', ddi: '370' },
  { name: 'Luxemburgo', code: 'LU', ddi: '352' },
  { name: 'Macau', code: 'MO', ddi: '853' },
  { name: 'Macedónia', code: 'MK', ddi: '389' },
  { name: 'Madagáscar', code: 'MG', ddi: '261' },
  { name: 'Malawi', code: 'MW', ddi: '265' },
  { name: 'Malásia', code: 'MY', ddi: '60' },
  { name: 'Maldivas', code: 'MV', ddi: '960' },
  { name: 'Mali', code: 'ML', ddi: '223' },
  { name: 'Malta', code: 'MT', ddi: '356' },
  { name: 'Mauritânia', code: 'MR', ddi: '222' },
  { name: 'Maurícia', code: 'MU', ddi: '230' },
  { name: 'Mayotte', code: 'YT', ddi: '262' },
  { name: 'México', code: 'MX', ddi: '52' },
  { name: 'Micronésia', code: 'FM', ddi: '691' },
  { name: 'Moldávia', code: 'MD', ddi: '373' },
  { name: 'Monaco', code: 'MC', ddi: '377' },
  { name: 'Mongólia', code: 'MN', ddi: '976' },
  { name: 'Montenegro', code: 'ME', ddi: '382' },
  { name: 'Montserrat', code: 'MS', ddi: '1 664' },
  { name: 'Marrocos', code: 'MA', ddi: '212' },
  { name: 'Moçambique', code: 'MZ', ddi: '258' },
  { name: 'Namíbia', code: 'NA', ddi: '264' },
  { name: 'Nauru', code: 'NR', ddi: '674' },
  { name: 'Nepal', code: 'NP', ddi: '977' },
  { name: 'Netherlands Antilles', code: 'AN', ddi: '599' },
  { name: 'Nova Caledônia', code: 'NC', ddi: '687' },
  { name: 'Nova Zelândia', code: 'NZ', ddi: '64' },
  { name: 'Nicaragua', code: 'NI', ddi: '505' },
  { name: 'Níger', code: 'NE', ddi: '227' },
  { name: 'Nigéria', code: 'NG', ddi: '234' },
  { name: 'Niue', code: 'NU', ddi: '683' },
  { name: 'Noruega', code: 'NO', ddi: '47' },
  { name: 'Omã', code: 'OM', ddi: '968' },
  { name: 'Países Baixos', code: 'NL', ddi: '31' },
  { name: 'Paquistão', code: 'PK', ddi: '92' },
  { name: 'Palau', code: 'PW', ddi: '680' },
  { name: 'Panamá', code: 'PA', ddi: '507' },
  { name: 'Papua-Nova Guiné', code: 'PG', ddi: '675' },
  { name: 'Paraguai', code: 'PY', ddi: '595' },
  { name: 'Peru', code: 'PE', ddi: '51' },
  { name: 'Filipinas', code: 'PH', ddi: '63' },
  { name: 'Polónia', code: 'PL', ddi: '48' },
  { name: 'Polinésia Francesa', code: 'PF', ddi: '689' },
  { name: 'Portugal', code: 'PT', ddi: '351' },
  { name: 'Porto Rico', code: 'PR', ddi: '1' },
  { name: 'República do Congo', code: 'CG', ddi: '242' },
  { name: 'República Democrática do Congo', code: 'CD', ddi: '243' },
  { name: 'República Centro-Africana', code: 'CF', ddi: '236' },
  { name: 'República Checa', code: 'CZ', ddi: '420' },
  { name: 'República Dominicana', code: 'DO', ddi: '1 809' },
  { name: 'Roménia', code: 'RO', ddi: '40' },
  { name: 'Ruanda', code: 'RW', ddi: '250' },
  { name: 'Rússia', code: 'RU', ddi: '7' },
  { name: 'Saint Barthelemy', code: 'BL', ddi: '590' },
  { name: 'Samoa', code: 'WS', ddi: '685' },
  { name: 'Samoa Americana', code: 'AS', ddi: '1 684' },
  { name: 'San Marino', code: 'SM', ddi: '378' },
  { name: 'Sao Tome e Principe', code: 'ST', ddi: '239' },
  { name: 'Senegal', code: 'SN', ddi: '221' },
  { name: 'Serbia', code: 'RS', ddi: '381' },
  { name: 'Serra Leoa', code: 'SL', ddi: '232' },
  { name: 'Seychelles', code: 'SC', ddi: '248' },
  { name: 'Slovakia', code: 'SK', ddi: '421' },
  { name: 'Slovenia', code: 'SI', ddi: '386' },
  { name: 'Somalia', code: 'SO', ddi: '252' },
  { name: 'Sri Lanka', code: 'LK', ddi: '94' },
  { name: 'Saint Helena', code: 'SH', ddi: '290' },
  { name: 'Saint Kitts and Nevis', code: 'KN', ddi: '1 869' },
  { name: 'Saint Lucia', code: 'LC', ddi: '1 758' },
  { name: 'Saint Martin', code: 'MF', ddi: '1 599' },
  { name: 'Saint Pierre and Miquelon', code: 'PM', ddi: '508' },
  { name: 'Saint Vincent and the Grenadines', code: 'VC', ddi: '1 784' },
  { name: 'Sudão', code: 'SD', ddi: '249' },
  { name: 'Suriname', code: 'SR', ddi: '597' },
  { name: 'Suazilândia', code: 'SZ', ddi: '268' },
  { name: 'Suécia', code: 'SE', ddi: '46' },
  { name: 'Suiça', code: 'CH', ddi: '41' },
  { name: 'Syria', code: 'SY', ddi: '963' },
  { name: 'Taiwan', code: 'TW', ddi: '886' },
  { name: 'Tajiquistão', code: 'TJ', ddi: '992' },
  { name: 'Tanzânia', code: 'TZ', ddi: '255' },
  { name: 'Timor-Leste', code: 'TL', ddi: '670' },
  { name: 'Tailândia', code: 'TH', ddi: '66' },
  { name: 'Togo', code: 'TG', ddi: '228' },
  { name: 'Tokelau', code: 'TK', ddi: '690' },
  { name: 'Tonga', code: 'TO', ddi: '676' },
  { name: 'Trinidad e Tobago', code: 'TT', ddi: '1 868' },
  { name: 'Tunísia', code: 'TN', ddi: '216' },
  { name: 'Turquemenistão', code: 'TM', ddi: '993' },
  { name: 'Turquia', code: 'TR', ddi: '90' },
  { name: 'Tuvalu', code: 'TV', ddi: '688' },
  { name: 'Uganda', code: 'UG', ddi: '256' },
  { name: 'Ucrânia', code: 'UA', ddi: '380' },
  { name: 'Uruguai', code: 'UY', ddi: '598' },
  { name: 'Estados Unidos (EUA)', code: 'US', ddi: '1' },
  { name: 'Uzbequistão', code: 'UZ', ddi: '998' },
  { name: 'Vanuatu', code: 'VU', ddi: '678' },
  { name: 'Vaticano', code: 'VA', ddi: '39' },
  { name: 'Venezuela', code: 'VE', ddi: '58' },
  { name: 'Vietnã (Vietname)', code: 'VN', ddi: '84' },
  { name: 'Wallis e Futuna', code: 'WF', ddi: '681' },
  { name: 'Iémen (Iémen, Yemen)', code: 'YE', ddi: '967' },
  { name: 'Zimbabwe(Zimbabué)', code: 'ZW', ddi: '263' },
  { name: 'Zâmbia', code: 'ZM', ddi: '260' }
]
